version: '3.8'

services:
  server:
    container_name: todo_backend
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/usr/app
    command: python manage.py runserver 0.0.0.0:8000

  web:
    container_name: todo_frontend
    build: ./frontend
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
